services:
  postgres:
    image: postgres:14.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    ports:
      - 5432

  api:
    image: ruby:3.2-rc
    working_dir: /app
    depends_on:
      - postgres
    volumes:
      - ./api:/app
      - api_bundle:/usr/local/bundle
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: $PG_USER
      PGPASSWORD: $PG_PASSWORD
      PGDB: $PG_DB
    command: [bundle, exec, puma]
    ports:
      - 127.0.0.1:3000:9292
    stdin_open: true
    tty: true


volumes:
  postgres:
  api_bundle:
